# Use the official Python image as a base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the consumer.py file into the container at /app
COPY kafka_consumer/consumer.py .

# Command to run the Kafka consumer
CMD ["python", "consumer.py"]
